position:
  class: sfPropelRouteCollection
  options:
    model:                position
    module:               position
    prefix_path:          /position
    column:               id_position
    with_wildcard_routes: true

zone:
  class: sfPropelRouteCollection
  options:
    model:                zone
    module:               zone
    prefix_path:          /zone
    column:               id_zone
    with_wildcard_routes: true

depto:
  class: sfPropelRouteCollection
  options:
    model:                depto
    module:               depto
    prefix_path:          /depto
    column:               id_depto
    with_wildcard_routes: true

area:
  class: sfPropelRouteCollection
  options:
    model:                area
    module:               area
    prefix_path:          /area
    column:               id_area
    with_wildcard_routes: true

sf_guard_user_profile:
  class: sfPropelRouteCollection
  options:
    model:                sfGuardUserProfile
    module:               sf_guard_user_profile
    prefix_path:          /sf_guard_user_profile
    column:               id
    with_wildcard_routes: true

quizusr:
  class: sfPropelRouteCollection
  options:
    model:                quizusr
    module:               quizusr
    prefix_path:          /quizusr
    column:               id_quiz_usr
    with_wildcard_routes: true

quizlog:
  class: sfPropelRouteCollection
  options:
    model:                quizlog
    module:               quizlog
    prefix_path:          /quizlog
    column:               id_quiz_usr_log
    with_wildcard_routes: true

instructions:
  class: sfPropelRouteCollection
  options:
    model:                instructions
    module:               instructions
    prefix_path:          /instructions
    column:               id_instruction
    with_wildcard_routes: true

dificulty_quiz:
  class: sfPropelRouteCollection
  options:
    model:                DificultyQuiz
    module:               dificulty_quiz
    prefix_path:          /dificulty_quiz
    column:               id_dif_quiz
    with_wildcard_routes: true

questions_quiz:
  class: sfPropelRouteCollection
  options:
    model:                questionsQuiz
    module:               questions_quiz
    prefix_path:          /questions_quiz
    column:               id_questions_quiz
    with_wildcard_routes: true

quiz:
  class: sfPropelRouteCollection
  options:
    model:                quiz
    module:               quiz
    prefix_path:          /quiz
    column:               id_quiz
    with_wildcard_routes: true

correct_answer_question:
  class: sfPropelRouteCollection
  options:
    model:                correctAnswerQuestion
    module:               correct_answer_question
    prefix_path:          /correct_answer_question
    column:               id_correct_answer_question
    with_wildcard_routes: true

dificulty:
  class: sfPropelRouteCollection
  options:
    model:                dificulty
    module:               dificulty
    prefix_path:          /dificulty
    column:               id_dificulty
    with_wildcard_routes: true

answer:
  class: sfPropelRouteCollection
  options:
    model:                answer
    module:               answer
    prefix_path:          /answer
    column:               id_answer
    with_wildcard_routes: true

question:
  class: sfPropelRouteCollection
  options:
    model:                question
    module:               question
    prefix_path:          /question
    column:               id_question
    with_wildcard_routes: true
    

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: dificulty_quiz, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:dificulty
  param: { action: index }

default:
  url:   /:@dificulty/:index/*
  
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
 
logout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
 
sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
  
help:
  url:   /help
  param: { module: instructions, action: help }
  
register:
  url:   /register
  param: { module: sfGuardUser, action: new }
  
profile:
  url:   /sf_guard_user
  param: { module: sf_guard_user, action: index }
