<?php


/**
 * This class defines the structure of the 'answer' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Mar  7 00:03:12 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AnswerTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AnswerTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('answer');
		$this->setPhpName('Answer');
		$this->setClassname('Answer');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID_ANSWER', 'IdAnswer', 'INTEGER', true, 10, null);
		$this->addColumn('ANSWER', 'Answer', 'VARCHAR', false, 200, '0');
		$this->addForeignKey('ID_QUESTION', 'IdQuestion', 'INTEGER', 'question', 'ID_QUESTION', false, 11, 0);
		$this->addColumn('CORRECT', 'Correct', 'SMALLINT', false, 6, 0);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Question', 'Question', RelationMap::MANY_TO_ONE, array('id_question' => 'id_question', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('CorrectAnswerQuestion', 'CorrectAnswerQuestion', RelationMap::ONE_TO_MANY, array('id_answer' => 'id_answer', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('Quizusr', 'Quizusr', RelationMap::ONE_TO_MANY, array('id_answer' => 'id_answer', ), 'RESTRICT', 'RESTRICT');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // AnswerTableMap
