<?php


/**
 * This class defines the structure of the 'perfil' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Apr 13 21:41:53 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PerfilTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PerfilTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('perfil');
		$this->setPhpName('Perfil');
		$this->setClassname('Perfil');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addColumn('CORREO', 'Correo', 'VARCHAR', false, 145, null);
		$this->addColumn('NOMBRE', 'Nombre', 'VARCHAR', false, 145, null);
		$this->addColumn('SEXO', 'Sexo', 'VARCHAR', false, 45, null);
		$this->addColumn('USUARIO', 'Usuario', 'VARCHAR', false, 145, null);
		$this->addColumn('CARGO', 'Cargo', 'VARCHAR', false, 145, null);
		$this->addColumn('COSTO', 'Costo', 'VARCHAR', false, 145, null);
		$this->addColumn('OFICINA', 'Oficina', 'VARCHAR', false, 145, null);
		$this->addColumn('ZONA', 'Zona', 'VARCHAR', false, 145, null);
		$this->addColumn('AREA', 'Area', 'VARCHAR', false, 245, null);
		$this->addColumn('ID_ZONA', 'IdZona', 'VARCHAR', false, 45, null);
		$this->addColumn('ID_OFICINA', 'IdOficina', 'VARCHAR', false, 45, null);
		$this->addColumn('ID_AREA', 'IdArea', 'VARCHAR', false, 45, null);
		$this->addColumn('ID_CARGO', 'IdCargo', 'VARCHAR', false, 45, null);
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // PerfilTableMap
