<?php


/**
 * This class defines the structure of the 'question' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Mar 19 22:56:42 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class QuestionTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.QuestionTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('question');
		$this->setPhpName('Question');
		$this->setClassname('Question');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID_QUESTION', 'IdQuestion', 'INTEGER', true, 10, null);
		$this->addColumn('QUESTION', 'Question', 'LONGVARCHAR', false, null, null);
		$this->addForeignKey('ID_DIFICULTAD', 'IdDificultad', 'INTEGER', 'dificulty', 'ID_DIFICULTY', false, 11, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Dificulty', 'Dificulty', RelationMap::MANY_TO_ONE, array('id_dificultad' => 'id_dificulty', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('Answer', 'Answer', RelationMap::ONE_TO_MANY, array('id_question' => 'id_question', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('CorrectAnswerQuestion', 'CorrectAnswerQuestion', RelationMap::ONE_TO_MANY, array('id_question' => 'id_question', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('QuestionsQuiz', 'QuestionsQuiz', RelationMap::ONE_TO_MANY, array('id_question' => 'id_question', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('Quizusr', 'Quizusr', RelationMap::ONE_TO_MANY, array('id_question' => 'id_question', ), 'RESTRICT', 'RESTRICT');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // QuestionTableMap
