<?php

/**
 * Base class that represents a row from the 'quiz' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Apr 13 21:41:54 2013
 *
 * @package    lib.model.om
 */
abstract class BaseQuiz extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        QuizPeer
	 */
	protected static $peer;

	/**
	 * The value for the id_quiz field.
	 * @var        int
	 */
	protected $id_quiz;

	/**
	 * The value for the description field.
	 * @var        string
	 */
	protected $description;

	/**
	 * The value for the inicial_time field.
	 * @var        string
	 */
	protected $inicial_time;

	/**
	 * The value for the final_time field.
	 * @var        string
	 */
	protected $final_time;

	/**
	 * The value for the status field.
	 * Note: this column has a database default value of: 1
	 * @var        int
	 */
	protected $status;

	/**
	 * @var        array BonusQuiz[] Collection to store aggregation of BonusQuiz objects.
	 */
	protected $collBonusQuizs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collBonusQuizs.
	 */
	private $lastBonusQuizCriteria = null;

	/**
	 * @var        array DificultyQuiz[] Collection to store aggregation of DificultyQuiz objects.
	 */
	protected $collDificultyQuizs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collDificultyQuizs.
	 */
	private $lastDificultyQuizCriteria = null;

	/**
	 * @var        array QuestionsQuiz[] Collection to store aggregation of QuestionsQuiz objects.
	 */
	protected $collQuestionsQuizs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collQuestionsQuizs.
	 */
	private $lastQuestionsQuizCriteria = null;

	/**
	 * @var        array Quizlog[] Collection to store aggregation of Quizlog objects.
	 */
	protected $collQuizlogs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collQuizlogs.
	 */
	private $lastQuizlogCriteria = null;

	/**
	 * @var        array Quizusr[] Collection to store aggregation of Quizusr objects.
	 */
	protected $collQuizusrs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collQuizusrs.
	 */
	private $lastQuizusrCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'QuizPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->status = 1;
	}

	/**
	 * Initializes internal state of BaseQuiz object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id_quiz] column value.
	 * 
	 * @return     int
	 */
	public function getIdQuiz()
	{
		return $this->id_quiz;
	}

	/**
	 * Get the [description] column value.
	 * 
	 * @return     string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Get the [optionally formatted] temporal [inicial_time] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getInicialTime($format = 'Y-m-d H:i:s')
	{
		if ($this->inicial_time === null) {
			return null;
		}


		if ($this->inicial_time === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->inicial_time);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->inicial_time, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [final_time] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFinalTime($format = 'Y-m-d H:i:s')
	{
		if ($this->final_time === null) {
			return null;
		}


		if ($this->final_time === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->final_time);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->final_time, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [status] column value.
	 * 
	 * @return     int
	 */
	public function getStatus()
	{
		return $this->status;
	}

	/**
	 * Set the value of [id_quiz] column.
	 * 
	 * @param      int $v new value
	 * @return     Quiz The current object (for fluent API support)
	 */
	public function setIdQuiz($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_quiz !== $v) {
			$this->id_quiz = $v;
			$this->modifiedColumns[] = QuizPeer::ID_QUIZ;
		}

		return $this;
	} // setIdQuiz()

	/**
	 * Set the value of [description] column.
	 * 
	 * @param      string $v new value
	 * @return     Quiz The current object (for fluent API support)
	 */
	public function setDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description !== $v) {
			$this->description = $v;
			$this->modifiedColumns[] = QuizPeer::DESCRIPTION;
		}

		return $this;
	} // setDescription()

	/**
	 * Sets the value of [inicial_time] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Quiz The current object (for fluent API support)
	 */
	public function setInicialTime($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->inicial_time !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->inicial_time !== null && $tmpDt = new DateTime($this->inicial_time)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->inicial_time = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = QuizPeer::INICIAL_TIME;
			}
		} // if either are not null

		return $this;
	} // setInicialTime()

	/**
	 * Sets the value of [final_time] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Quiz The current object (for fluent API support)
	 */
	public function setFinalTime($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->final_time !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->final_time !== null && $tmpDt = new DateTime($this->final_time)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->final_time = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = QuizPeer::FINAL_TIME;
			}
		} // if either are not null

		return $this;
	} // setFinalTime()

	/**
	 * Set the value of [status] column.
	 * 
	 * @param      int $v new value
	 * @return     Quiz The current object (for fluent API support)
	 */
	public function setStatus($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->status !== $v || $this->isNew()) {
			$this->status = $v;
			$this->modifiedColumns[] = QuizPeer::STATUS;
		}

		return $this;
	} // setStatus()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->status !== 1) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id_quiz = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->description = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->inicial_time = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->final_time = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->status = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 5; // 5 = QuizPeer::NUM_COLUMNS - QuizPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Quiz object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(QuizPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = QuizPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collBonusQuizs = null;
			$this->lastBonusQuizCriteria = null;

			$this->collDificultyQuizs = null;
			$this->lastDificultyQuizCriteria = null;

			$this->collQuestionsQuizs = null;
			$this->lastQuestionsQuizCriteria = null;

			$this->collQuizlogs = null;
			$this->lastQuizlogCriteria = null;

			$this->collQuizusrs = null;
			$this->lastQuizusrCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(QuizPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseQuiz:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				QuizPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseQuiz:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(QuizPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseQuiz:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseQuiz:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				QuizPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = QuizPeer::ID_QUIZ;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = QuizPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setIdQuiz($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += QuizPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collBonusQuizs !== null) {
				foreach ($this->collBonusQuizs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collDificultyQuizs !== null) {
				foreach ($this->collDificultyQuizs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collQuestionsQuizs !== null) {
				foreach ($this->collQuestionsQuizs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collQuizlogs !== null) {
				foreach ($this->collQuizlogs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collQuizusrs !== null) {
				foreach ($this->collQuizusrs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = QuizPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collBonusQuizs !== null) {
					foreach ($this->collBonusQuizs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collDificultyQuizs !== null) {
					foreach ($this->collDificultyQuizs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collQuestionsQuizs !== null) {
					foreach ($this->collQuestionsQuizs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collQuizlogs !== null) {
					foreach ($this->collQuizlogs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collQuizusrs !== null) {
					foreach ($this->collQuizusrs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = QuizPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdQuiz();
				break;
			case 1:
				return $this->getDescription();
				break;
			case 2:
				return $this->getInicialTime();
				break;
			case 3:
				return $this->getFinalTime();
				break;
			case 4:
				return $this->getStatus();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = QuizPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIdQuiz(),
			$keys[1] => $this->getDescription(),
			$keys[2] => $this->getInicialTime(),
			$keys[3] => $this->getFinalTime(),
			$keys[4] => $this->getStatus(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = QuizPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdQuiz($value);
				break;
			case 1:
				$this->setDescription($value);
				break;
			case 2:
				$this->setInicialTime($value);
				break;
			case 3:
				$this->setFinalTime($value);
				break;
			case 4:
				$this->setStatus($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = QuizPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdQuiz($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setDescription($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setInicialTime($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setFinalTime($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setStatus($arr[$keys[4]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(QuizPeer::DATABASE_NAME);

		if ($this->isColumnModified(QuizPeer::ID_QUIZ)) $criteria->add(QuizPeer::ID_QUIZ, $this->id_quiz);
		if ($this->isColumnModified(QuizPeer::DESCRIPTION)) $criteria->add(QuizPeer::DESCRIPTION, $this->description);
		if ($this->isColumnModified(QuizPeer::INICIAL_TIME)) $criteria->add(QuizPeer::INICIAL_TIME, $this->inicial_time);
		if ($this->isColumnModified(QuizPeer::FINAL_TIME)) $criteria->add(QuizPeer::FINAL_TIME, $this->final_time);
		if ($this->isColumnModified(QuizPeer::STATUS)) $criteria->add(QuizPeer::STATUS, $this->status);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(QuizPeer::DATABASE_NAME);

		$criteria->add(QuizPeer::ID_QUIZ, $this->id_quiz);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getIdQuiz();
	}

	/**
	 * Generic method to set the primary key (id_quiz column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIdQuiz($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Quiz (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setDescription($this->description);

		$copyObj->setInicialTime($this->inicial_time);

		$copyObj->setFinalTime($this->final_time);

		$copyObj->setStatus($this->status);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getBonusQuizs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addBonusQuiz($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getDificultyQuizs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addDificultyQuiz($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getQuestionsQuizs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addQuestionsQuiz($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getQuizlogs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addQuizlog($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getQuizusrs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addQuizusr($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setIdQuiz(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Quiz Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     QuizPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new QuizPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collBonusQuizs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addBonusQuizs()
	 */
	public function clearBonusQuizs()
	{
		$this->collBonusQuizs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collBonusQuizs collection (array).
	 *
	 * By default this just sets the collBonusQuizs collection to an empty array (like clearcollBonusQuizs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initBonusQuizs()
	{
		$this->collBonusQuizs = array();
	}

	/**
	 * Gets an array of BonusQuiz objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Quiz has previously been saved, it will retrieve
	 * related BonusQuizs from storage. If this Quiz is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array BonusQuiz[]
	 * @throws     PropelException
	 */
	public function getBonusQuizs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuizPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collBonusQuizs === null) {
			if ($this->isNew()) {
			   $this->collBonusQuizs = array();
			} else {

				$criteria->add(BonusQuizPeer::ID_QUIZ, $this->id_quiz);

				BonusQuizPeer::addSelectColumns($criteria);
				$this->collBonusQuizs = BonusQuizPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(BonusQuizPeer::ID_QUIZ, $this->id_quiz);

				BonusQuizPeer::addSelectColumns($criteria);
				if (!isset($this->lastBonusQuizCriteria) || !$this->lastBonusQuizCriteria->equals($criteria)) {
					$this->collBonusQuizs = BonusQuizPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastBonusQuizCriteria = $criteria;
		return $this->collBonusQuizs;
	}

	/**
	 * Returns the number of related BonusQuiz objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related BonusQuiz objects.
	 * @throws     PropelException
	 */
	public function countBonusQuizs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuizPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collBonusQuizs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(BonusQuizPeer::ID_QUIZ, $this->id_quiz);

				$count = BonusQuizPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(BonusQuizPeer::ID_QUIZ, $this->id_quiz);

				if (!isset($this->lastBonusQuizCriteria) || !$this->lastBonusQuizCriteria->equals($criteria)) {
					$count = BonusQuizPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collBonusQuizs);
				}
			} else {
				$count = count($this->collBonusQuizs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a BonusQuiz object to this object
	 * through the BonusQuiz foreign key attribute.
	 *
	 * @param      BonusQuiz $l BonusQuiz
	 * @return     void
	 * @throws     PropelException
	 */
	public function addBonusQuiz(BonusQuiz $l)
	{
		if ($this->collBonusQuizs === null) {
			$this->initBonusQuizs();
		}
		if (!in_array($l, $this->collBonusQuizs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collBonusQuizs, $l);
			$l->setQuiz($this);
		}
	}

	/**
	 * Clears out the collDificultyQuizs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addDificultyQuizs()
	 */
	public function clearDificultyQuizs()
	{
		$this->collDificultyQuizs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collDificultyQuizs collection (array).
	 *
	 * By default this just sets the collDificultyQuizs collection to an empty array (like clearcollDificultyQuizs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initDificultyQuizs()
	{
		$this->collDificultyQuizs = array();
	}

	/**
	 * Gets an array of DificultyQuiz objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Quiz has previously been saved, it will retrieve
	 * related DificultyQuizs from storage. If this Quiz is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array DificultyQuiz[]
	 * @throws     PropelException
	 */
	public function getDificultyQuizs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuizPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collDificultyQuizs === null) {
			if ($this->isNew()) {
			   $this->collDificultyQuizs = array();
			} else {

				$criteria->add(DificultyQuizPeer::ID_QUIZ, $this->id_quiz);

				DificultyQuizPeer::addSelectColumns($criteria);
				$this->collDificultyQuizs = DificultyQuizPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(DificultyQuizPeer::ID_QUIZ, $this->id_quiz);

				DificultyQuizPeer::addSelectColumns($criteria);
				if (!isset($this->lastDificultyQuizCriteria) || !$this->lastDificultyQuizCriteria->equals($criteria)) {
					$this->collDificultyQuizs = DificultyQuizPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastDificultyQuizCriteria = $criteria;
		return $this->collDificultyQuizs;
	}

	/**
	 * Returns the number of related DificultyQuiz objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related DificultyQuiz objects.
	 * @throws     PropelException
	 */
	public function countDificultyQuizs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuizPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collDificultyQuizs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(DificultyQuizPeer::ID_QUIZ, $this->id_quiz);

				$count = DificultyQuizPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(DificultyQuizPeer::ID_QUIZ, $this->id_quiz);

				if (!isset($this->lastDificultyQuizCriteria) || !$this->lastDificultyQuizCriteria->equals($criteria)) {
					$count = DificultyQuizPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collDificultyQuizs);
				}
			} else {
				$count = count($this->collDificultyQuizs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a DificultyQuiz object to this object
	 * through the DificultyQuiz foreign key attribute.
	 *
	 * @param      DificultyQuiz $l DificultyQuiz
	 * @return     void
	 * @throws     PropelException
	 */
	public function addDificultyQuiz(DificultyQuiz $l)
	{
		if ($this->collDificultyQuizs === null) {
			$this->initDificultyQuizs();
		}
		if (!in_array($l, $this->collDificultyQuizs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collDificultyQuizs, $l);
			$l->setQuiz($this);
		}
	}

	/**
	 * Clears out the collQuestionsQuizs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addQuestionsQuizs()
	 */
	public function clearQuestionsQuizs()
	{
		$this->collQuestionsQuizs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collQuestionsQuizs collection (array).
	 *
	 * By default this just sets the collQuestionsQuizs collection to an empty array (like clearcollQuestionsQuizs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initQuestionsQuizs()
	{
		$this->collQuestionsQuizs = array();
	}

	/**
	 * Gets an array of QuestionsQuiz objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Quiz has previously been saved, it will retrieve
	 * related QuestionsQuizs from storage. If this Quiz is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array QuestionsQuiz[]
	 * @throws     PropelException
	 */
	public function getQuestionsQuizs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuizPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collQuestionsQuizs === null) {
			if ($this->isNew()) {
			   $this->collQuestionsQuizs = array();
			} else {

				$criteria->add(QuestionsQuizPeer::ID_QUIZ, $this->id_quiz);

				QuestionsQuizPeer::addSelectColumns($criteria);
				$this->collQuestionsQuizs = QuestionsQuizPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(QuestionsQuizPeer::ID_QUIZ, $this->id_quiz);

				QuestionsQuizPeer::addSelectColumns($criteria);
				if (!isset($this->lastQuestionsQuizCriteria) || !$this->lastQuestionsQuizCriteria->equals($criteria)) {
					$this->collQuestionsQuizs = QuestionsQuizPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastQuestionsQuizCriteria = $criteria;
		return $this->collQuestionsQuizs;
	}

	/**
	 * Returns the number of related QuestionsQuiz objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related QuestionsQuiz objects.
	 * @throws     PropelException
	 */
	public function countQuestionsQuizs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuizPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collQuestionsQuizs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(QuestionsQuizPeer::ID_QUIZ, $this->id_quiz);

				$count = QuestionsQuizPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(QuestionsQuizPeer::ID_QUIZ, $this->id_quiz);

				if (!isset($this->lastQuestionsQuizCriteria) || !$this->lastQuestionsQuizCriteria->equals($criteria)) {
					$count = QuestionsQuizPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collQuestionsQuizs);
				}
			} else {
				$count = count($this->collQuestionsQuizs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a QuestionsQuiz object to this object
	 * through the QuestionsQuiz foreign key attribute.
	 *
	 * @param      QuestionsQuiz $l QuestionsQuiz
	 * @return     void
	 * @throws     PropelException
	 */
	public function addQuestionsQuiz(QuestionsQuiz $l)
	{
		if ($this->collQuestionsQuizs === null) {
			$this->initQuestionsQuizs();
		}
		if (!in_array($l, $this->collQuestionsQuizs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collQuestionsQuizs, $l);
			$l->setQuiz($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Quiz is new, it will return
	 * an empty collection; or if this Quiz has previously
	 * been saved, it will retrieve related QuestionsQuizs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Quiz.
	 */
	public function getQuestionsQuizsJoinQuestion($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuizPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collQuestionsQuizs === null) {
			if ($this->isNew()) {
				$this->collQuestionsQuizs = array();
			} else {

				$criteria->add(QuestionsQuizPeer::ID_QUIZ, $this->id_quiz);

				$this->collQuestionsQuizs = QuestionsQuizPeer::doSelectJoinQuestion($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(QuestionsQuizPeer::ID_QUIZ, $this->id_quiz);

			if (!isset($this->lastQuestionsQuizCriteria) || !$this->lastQuestionsQuizCriteria->equals($criteria)) {
				$this->collQuestionsQuizs = QuestionsQuizPeer::doSelectJoinQuestion($criteria, $con, $join_behavior);
			}
		}
		$this->lastQuestionsQuizCriteria = $criteria;

		return $this->collQuestionsQuizs;
	}

	/**
	 * Clears out the collQuizlogs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addQuizlogs()
	 */
	public function clearQuizlogs()
	{
		$this->collQuizlogs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collQuizlogs collection (array).
	 *
	 * By default this just sets the collQuizlogs collection to an empty array (like clearcollQuizlogs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initQuizlogs()
	{
		$this->collQuizlogs = array();
	}

	/**
	 * Gets an array of Quizlog objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Quiz has previously been saved, it will retrieve
	 * related Quizlogs from storage. If this Quiz is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Quizlog[]
	 * @throws     PropelException
	 */
	public function getQuizlogs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuizPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collQuizlogs === null) {
			if ($this->isNew()) {
			   $this->collQuizlogs = array();
			} else {

				$criteria->add(QuizlogPeer::ID_QUIZLOG, $this->id_quiz);

				QuizlogPeer::addSelectColumns($criteria);
				$this->collQuizlogs = QuizlogPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(QuizlogPeer::ID_QUIZLOG, $this->id_quiz);

				QuizlogPeer::addSelectColumns($criteria);
				if (!isset($this->lastQuizlogCriteria) || !$this->lastQuizlogCriteria->equals($criteria)) {
					$this->collQuizlogs = QuizlogPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastQuizlogCriteria = $criteria;
		return $this->collQuizlogs;
	}

	/**
	 * Returns the number of related Quizlog objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Quizlog objects.
	 * @throws     PropelException
	 */
	public function countQuizlogs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuizPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collQuizlogs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(QuizlogPeer::ID_QUIZLOG, $this->id_quiz);

				$count = QuizlogPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(QuizlogPeer::ID_QUIZLOG, $this->id_quiz);

				if (!isset($this->lastQuizlogCriteria) || !$this->lastQuizlogCriteria->equals($criteria)) {
					$count = QuizlogPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collQuizlogs);
				}
			} else {
				$count = count($this->collQuizlogs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Quizlog object to this object
	 * through the Quizlog foreign key attribute.
	 *
	 * @param      Quizlog $l Quizlog
	 * @return     void
	 * @throws     PropelException
	 */
	public function addQuizlog(Quizlog $l)
	{
		if ($this->collQuizlogs === null) {
			$this->initQuizlogs();
		}
		if (!in_array($l, $this->collQuizlogs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collQuizlogs, $l);
			$l->setQuiz($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Quiz is new, it will return
	 * an empty collection; or if this Quiz has previously
	 * been saved, it will retrieve related Quizlogs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Quiz.
	 */
	public function getQuizlogsJoinSfGuardUserProfile($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuizPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collQuizlogs === null) {
			if ($this->isNew()) {
				$this->collQuizlogs = array();
			} else {

				$criteria->add(QuizlogPeer::ID_QUIZLOG, $this->id_quiz);

				$this->collQuizlogs = QuizlogPeer::doSelectJoinSfGuardUserProfile($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(QuizlogPeer::ID_QUIZLOG, $this->id_quiz);

			if (!isset($this->lastQuizlogCriteria) || !$this->lastQuizlogCriteria->equals($criteria)) {
				$this->collQuizlogs = QuizlogPeer::doSelectJoinSfGuardUserProfile($criteria, $con, $join_behavior);
			}
		}
		$this->lastQuizlogCriteria = $criteria;

		return $this->collQuizlogs;
	}

	/**
	 * Clears out the collQuizusrs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addQuizusrs()
	 */
	public function clearQuizusrs()
	{
		$this->collQuizusrs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collQuizusrs collection (array).
	 *
	 * By default this just sets the collQuizusrs collection to an empty array (like clearcollQuizusrs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initQuizusrs()
	{
		$this->collQuizusrs = array();
	}

	/**
	 * Gets an array of Quizusr objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Quiz has previously been saved, it will retrieve
	 * related Quizusrs from storage. If this Quiz is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Quizusr[]
	 * @throws     PropelException
	 */
	public function getQuizusrs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuizPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collQuizusrs === null) {
			if ($this->isNew()) {
			   $this->collQuizusrs = array();
			} else {

				$criteria->add(QuizusrPeer::ID_QUIZ, $this->id_quiz);

				QuizusrPeer::addSelectColumns($criteria);
				$this->collQuizusrs = QuizusrPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(QuizusrPeer::ID_QUIZ, $this->id_quiz);

				QuizusrPeer::addSelectColumns($criteria);
				if (!isset($this->lastQuizusrCriteria) || !$this->lastQuizusrCriteria->equals($criteria)) {
					$this->collQuizusrs = QuizusrPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastQuizusrCriteria = $criteria;
		return $this->collQuizusrs;
	}

	/**
	 * Returns the number of related Quizusr objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Quizusr objects.
	 * @throws     PropelException
	 */
	public function countQuizusrs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuizPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collQuizusrs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(QuizusrPeer::ID_QUIZ, $this->id_quiz);

				$count = QuizusrPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(QuizusrPeer::ID_QUIZ, $this->id_quiz);

				if (!isset($this->lastQuizusrCriteria) || !$this->lastQuizusrCriteria->equals($criteria)) {
					$count = QuizusrPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collQuizusrs);
				}
			} else {
				$count = count($this->collQuizusrs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Quizusr object to this object
	 * through the Quizusr foreign key attribute.
	 *
	 * @param      Quizusr $l Quizusr
	 * @return     void
	 * @throws     PropelException
	 */
	public function addQuizusr(Quizusr $l)
	{
		if ($this->collQuizusrs === null) {
			$this->initQuizusrs();
		}
		if (!in_array($l, $this->collQuizusrs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collQuizusrs, $l);
			$l->setQuiz($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Quiz is new, it will return
	 * an empty collection; or if this Quiz has previously
	 * been saved, it will retrieve related Quizusrs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Quiz.
	 */
	public function getQuizusrsJoinQuestion($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuizPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collQuizusrs === null) {
			if ($this->isNew()) {
				$this->collQuizusrs = array();
			} else {

				$criteria->add(QuizusrPeer::ID_QUIZ, $this->id_quiz);

				$this->collQuizusrs = QuizusrPeer::doSelectJoinQuestion($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(QuizusrPeer::ID_QUIZ, $this->id_quiz);

			if (!isset($this->lastQuizusrCriteria) || !$this->lastQuizusrCriteria->equals($criteria)) {
				$this->collQuizusrs = QuizusrPeer::doSelectJoinQuestion($criteria, $con, $join_behavior);
			}
		}
		$this->lastQuizusrCriteria = $criteria;

		return $this->collQuizusrs;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Quiz is new, it will return
	 * an empty collection; or if this Quiz has previously
	 * been saved, it will retrieve related Quizusrs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Quiz.
	 */
	public function getQuizusrsJoinAnswer($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuizPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collQuizusrs === null) {
			if ($this->isNew()) {
				$this->collQuizusrs = array();
			} else {

				$criteria->add(QuizusrPeer::ID_QUIZ, $this->id_quiz);

				$this->collQuizusrs = QuizusrPeer::doSelectJoinAnswer($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(QuizusrPeer::ID_QUIZ, $this->id_quiz);

			if (!isset($this->lastQuizusrCriteria) || !$this->lastQuizusrCriteria->equals($criteria)) {
				$this->collQuizusrs = QuizusrPeer::doSelectJoinAnswer($criteria, $con, $join_behavior);
			}
		}
		$this->lastQuizusrCriteria = $criteria;

		return $this->collQuizusrs;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collBonusQuizs) {
				foreach ((array) $this->collBonusQuizs as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collDificultyQuizs) {
				foreach ((array) $this->collDificultyQuizs as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collQuestionsQuizs) {
				foreach ((array) $this->collQuestionsQuizs as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collQuizlogs) {
				foreach ((array) $this->collQuizlogs as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collQuizusrs) {
				foreach ((array) $this->collQuizusrs as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collBonusQuizs = null;
		$this->collDificultyQuizs = null;
		$this->collQuestionsQuizs = null;
		$this->collQuizlogs = null;
		$this->collQuizusrs = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseQuiz:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseQuiz::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseQuiz
