<?php

/**
 * Base class that represents a row from the 'question' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Apr 13 21:41:53 2013
 *
 * @package    lib.model.om
 */
abstract class BaseQuestion extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        QuestionPeer
	 */
	protected static $peer;

	/**
	 * The value for the id_question field.
	 * @var        int
	 */
	protected $id_question;

	/**
	 * The value for the question field.
	 * @var        string
	 */
	protected $question;

	/**
	 * The value for the id_dificultad field.
	 * @var        int
	 */
	protected $id_dificultad;

	/**
	 * @var        Dificulty
	 */
	protected $aDificulty;

	/**
	 * @var        array Answer[] Collection to store aggregation of Answer objects.
	 */
	protected $collAnswers;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAnswers.
	 */
	private $lastAnswerCriteria = null;

	/**
	 * @var        array CorrectAnswerQuestion[] Collection to store aggregation of CorrectAnswerQuestion objects.
	 */
	protected $collCorrectAnswerQuestions;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCorrectAnswerQuestions.
	 */
	private $lastCorrectAnswerQuestionCriteria = null;

	/**
	 * @var        array QuestionsQuiz[] Collection to store aggregation of QuestionsQuiz objects.
	 */
	protected $collQuestionsQuizs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collQuestionsQuizs.
	 */
	private $lastQuestionsQuizCriteria = null;

	/**
	 * @var        array Quizusr[] Collection to store aggregation of Quizusr objects.
	 */
	protected $collQuizusrs;

	/**
	 * @var        Criteria The criteria used to select the current contents of collQuizusrs.
	 */
	private $lastQuizusrCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'QuestionPeer';

	/**
	 * Get the [id_question] column value.
	 * 
	 * @return     int
	 */
	public function getIdQuestion()
	{
		return $this->id_question;
	}

	/**
	 * Get the [question] column value.
	 * 
	 * @return     string
	 */
	public function getQuestion()
	{
		return $this->question;
	}

	/**
	 * Get the [id_dificultad] column value.
	 * 
	 * @return     int
	 */
	public function getIdDificultad()
	{
		return $this->id_dificultad;
	}

	/**
	 * Set the value of [id_question] column.
	 * 
	 * @param      int $v new value
	 * @return     Question The current object (for fluent API support)
	 */
	public function setIdQuestion($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_question !== $v) {
			$this->id_question = $v;
			$this->modifiedColumns[] = QuestionPeer::ID_QUESTION;
		}

		return $this;
	} // setIdQuestion()

	/**
	 * Set the value of [question] column.
	 * 
	 * @param      string $v new value
	 * @return     Question The current object (for fluent API support)
	 */
	public function setQuestion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->question !== $v) {
			$this->question = $v;
			$this->modifiedColumns[] = QuestionPeer::QUESTION;
		}

		return $this;
	} // setQuestion()

	/**
	 * Set the value of [id_dificultad] column.
	 * 
	 * @param      int $v new value
	 * @return     Question The current object (for fluent API support)
	 */
	public function setIdDificultad($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_dificultad !== $v) {
			$this->id_dificultad = $v;
			$this->modifiedColumns[] = QuestionPeer::ID_DIFICULTAD;
		}

		if ($this->aDificulty !== null && $this->aDificulty->getIdDificulty() !== $v) {
			$this->aDificulty = null;
		}

		return $this;
	} // setIdDificultad()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id_question = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->question = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->id_dificultad = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 3; // 3 = QuestionPeer::NUM_COLUMNS - QuestionPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Question object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aDificulty !== null && $this->id_dificultad !== $this->aDificulty->getIdDificulty()) {
			$this->aDificulty = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(QuestionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = QuestionPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aDificulty = null;
			$this->collAnswers = null;
			$this->lastAnswerCriteria = null;

			$this->collCorrectAnswerQuestions = null;
			$this->lastCorrectAnswerQuestionCriteria = null;

			$this->collQuestionsQuizs = null;
			$this->lastQuestionsQuizCriteria = null;

			$this->collQuizusrs = null;
			$this->lastQuizusrCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(QuestionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseQuestion:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				QuestionPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseQuestion:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(QuestionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseQuestion:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseQuestion:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				QuestionPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aDificulty !== null) {
				if ($this->aDificulty->isModified() || $this->aDificulty->isNew()) {
					$affectedRows += $this->aDificulty->save($con);
				}
				$this->setDificulty($this->aDificulty);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = QuestionPeer::ID_QUESTION;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = QuestionPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setIdQuestion($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += QuestionPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAnswers !== null) {
				foreach ($this->collAnswers as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collCorrectAnswerQuestions !== null) {
				foreach ($this->collCorrectAnswerQuestions as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collQuestionsQuizs !== null) {
				foreach ($this->collQuestionsQuizs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collQuizusrs !== null) {
				foreach ($this->collQuizusrs as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aDificulty !== null) {
				if (!$this->aDificulty->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aDificulty->getValidationFailures());
				}
			}


			if (($retval = QuestionPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collAnswers !== null) {
					foreach ($this->collAnswers as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collCorrectAnswerQuestions !== null) {
					foreach ($this->collCorrectAnswerQuestions as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collQuestionsQuizs !== null) {
					foreach ($this->collQuestionsQuizs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collQuizusrs !== null) {
					foreach ($this->collQuizusrs as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = QuestionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdQuestion();
				break;
			case 1:
				return $this->getQuestion();
				break;
			case 2:
				return $this->getIdDificultad();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = QuestionPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getIdQuestion(),
			$keys[1] => $this->getQuestion(),
			$keys[2] => $this->getIdDificultad(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = QuestionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdQuestion($value);
				break;
			case 1:
				$this->setQuestion($value);
				break;
			case 2:
				$this->setIdDificultad($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = QuestionPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdQuestion($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setQuestion($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setIdDificultad($arr[$keys[2]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(QuestionPeer::DATABASE_NAME);

		if ($this->isColumnModified(QuestionPeer::ID_QUESTION)) $criteria->add(QuestionPeer::ID_QUESTION, $this->id_question);
		if ($this->isColumnModified(QuestionPeer::QUESTION)) $criteria->add(QuestionPeer::QUESTION, $this->question);
		if ($this->isColumnModified(QuestionPeer::ID_DIFICULTAD)) $criteria->add(QuestionPeer::ID_DIFICULTAD, $this->id_dificultad);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(QuestionPeer::DATABASE_NAME);

		$criteria->add(QuestionPeer::ID_QUESTION, $this->id_question);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getIdQuestion();
	}

	/**
	 * Generic method to set the primary key (id_question column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIdQuestion($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Question (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setQuestion($this->question);

		$copyObj->setIdDificultad($this->id_dificultad);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAnswers() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAnswer($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getCorrectAnswerQuestions() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCorrectAnswerQuestion($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getQuestionsQuizs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addQuestionsQuiz($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getQuizusrs() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addQuizusr($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setIdQuestion(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Question Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     QuestionPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new QuestionPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Dificulty object.
	 *
	 * @param      Dificulty $v
	 * @return     Question The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setDificulty(Dificulty $v = null)
	{
		if ($v === null) {
			$this->setIdDificultad(NULL);
		} else {
			$this->setIdDificultad($v->getIdDificulty());
		}

		$this->aDificulty = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Dificulty object, it will not be re-added.
		if ($v !== null) {
			$v->addQuestion($this);
		}

		return $this;
	}


	/**
	 * Get the associated Dificulty object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Dificulty The associated Dificulty object.
	 * @throws     PropelException
	 */
	public function getDificulty(PropelPDO $con = null)
	{
		if ($this->aDificulty === null && ($this->id_dificultad !== null)) {
			$this->aDificulty = DificultyPeer::retrieveByPk($this->id_dificultad);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aDificulty->addQuestions($this);
			 */
		}
		return $this->aDificulty;
	}

	/**
	 * Clears out the collAnswers collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAnswers()
	 */
	public function clearAnswers()
	{
		$this->collAnswers = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAnswers collection (array).
	 *
	 * By default this just sets the collAnswers collection to an empty array (like clearcollAnswers());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAnswers()
	{
		$this->collAnswers = array();
	}

	/**
	 * Gets an array of Answer objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Question has previously been saved, it will retrieve
	 * related Answers from storage. If this Question is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Answer[]
	 * @throws     PropelException
	 */
	public function getAnswers($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAnswers === null) {
			if ($this->isNew()) {
			   $this->collAnswers = array();
			} else {

				$criteria->add(AnswerPeer::ID_QUESTION, $this->id_question);

				AnswerPeer::addSelectColumns($criteria);
				$this->collAnswers = AnswerPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AnswerPeer::ID_QUESTION, $this->id_question);

				AnswerPeer::addSelectColumns($criteria);
				if (!isset($this->lastAnswerCriteria) || !$this->lastAnswerCriteria->equals($criteria)) {
					$this->collAnswers = AnswerPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAnswerCriteria = $criteria;
		return $this->collAnswers;
	}

	/**
	 * Returns the number of related Answer objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Answer objects.
	 * @throws     PropelException
	 */
	public function countAnswers(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAnswers === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AnswerPeer::ID_QUESTION, $this->id_question);

				$count = AnswerPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AnswerPeer::ID_QUESTION, $this->id_question);

				if (!isset($this->lastAnswerCriteria) || !$this->lastAnswerCriteria->equals($criteria)) {
					$count = AnswerPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collAnswers);
				}
			} else {
				$count = count($this->collAnswers);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Answer object to this object
	 * through the Answer foreign key attribute.
	 *
	 * @param      Answer $l Answer
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAnswer(Answer $l)
	{
		if ($this->collAnswers === null) {
			$this->initAnswers();
		}
		if (!in_array($l, $this->collAnswers, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAnswers, $l);
			$l->setQuestion($this);
		}
	}

	/**
	 * Clears out the collCorrectAnswerQuestions collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCorrectAnswerQuestions()
	 */
	public function clearCorrectAnswerQuestions()
	{
		$this->collCorrectAnswerQuestions = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCorrectAnswerQuestions collection (array).
	 *
	 * By default this just sets the collCorrectAnswerQuestions collection to an empty array (like clearcollCorrectAnswerQuestions());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCorrectAnswerQuestions()
	{
		$this->collCorrectAnswerQuestions = array();
	}

	/**
	 * Gets an array of CorrectAnswerQuestion objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Question has previously been saved, it will retrieve
	 * related CorrectAnswerQuestions from storage. If this Question is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array CorrectAnswerQuestion[]
	 * @throws     PropelException
	 */
	public function getCorrectAnswerQuestions($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCorrectAnswerQuestions === null) {
			if ($this->isNew()) {
			   $this->collCorrectAnswerQuestions = array();
			} else {

				$criteria->add(CorrectAnswerQuestionPeer::ID_QUESTION, $this->id_question);

				CorrectAnswerQuestionPeer::addSelectColumns($criteria);
				$this->collCorrectAnswerQuestions = CorrectAnswerQuestionPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CorrectAnswerQuestionPeer::ID_QUESTION, $this->id_question);

				CorrectAnswerQuestionPeer::addSelectColumns($criteria);
				if (!isset($this->lastCorrectAnswerQuestionCriteria) || !$this->lastCorrectAnswerQuestionCriteria->equals($criteria)) {
					$this->collCorrectAnswerQuestions = CorrectAnswerQuestionPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCorrectAnswerQuestionCriteria = $criteria;
		return $this->collCorrectAnswerQuestions;
	}

	/**
	 * Returns the number of related CorrectAnswerQuestion objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related CorrectAnswerQuestion objects.
	 * @throws     PropelException
	 */
	public function countCorrectAnswerQuestions(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCorrectAnswerQuestions === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CorrectAnswerQuestionPeer::ID_QUESTION, $this->id_question);

				$count = CorrectAnswerQuestionPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CorrectAnswerQuestionPeer::ID_QUESTION, $this->id_question);

				if (!isset($this->lastCorrectAnswerQuestionCriteria) || !$this->lastCorrectAnswerQuestionCriteria->equals($criteria)) {
					$count = CorrectAnswerQuestionPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collCorrectAnswerQuestions);
				}
			} else {
				$count = count($this->collCorrectAnswerQuestions);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a CorrectAnswerQuestion object to this object
	 * through the CorrectAnswerQuestion foreign key attribute.
	 *
	 * @param      CorrectAnswerQuestion $l CorrectAnswerQuestion
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCorrectAnswerQuestion(CorrectAnswerQuestion $l)
	{
		if ($this->collCorrectAnswerQuestions === null) {
			$this->initCorrectAnswerQuestions();
		}
		if (!in_array($l, $this->collCorrectAnswerQuestions, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCorrectAnswerQuestions, $l);
			$l->setQuestion($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Question is new, it will return
	 * an empty collection; or if this Question has previously
	 * been saved, it will retrieve related CorrectAnswerQuestions from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Question.
	 */
	public function getCorrectAnswerQuestionsJoinAnswer($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCorrectAnswerQuestions === null) {
			if ($this->isNew()) {
				$this->collCorrectAnswerQuestions = array();
			} else {

				$criteria->add(CorrectAnswerQuestionPeer::ID_QUESTION, $this->id_question);

				$this->collCorrectAnswerQuestions = CorrectAnswerQuestionPeer::doSelectJoinAnswer($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(CorrectAnswerQuestionPeer::ID_QUESTION, $this->id_question);

			if (!isset($this->lastCorrectAnswerQuestionCriteria) || !$this->lastCorrectAnswerQuestionCriteria->equals($criteria)) {
				$this->collCorrectAnswerQuestions = CorrectAnswerQuestionPeer::doSelectJoinAnswer($criteria, $con, $join_behavior);
			}
		}
		$this->lastCorrectAnswerQuestionCriteria = $criteria;

		return $this->collCorrectAnswerQuestions;
	}

	/**
	 * Clears out the collQuestionsQuizs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addQuestionsQuizs()
	 */
	public function clearQuestionsQuizs()
	{
		$this->collQuestionsQuizs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collQuestionsQuizs collection (array).
	 *
	 * By default this just sets the collQuestionsQuizs collection to an empty array (like clearcollQuestionsQuizs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initQuestionsQuizs()
	{
		$this->collQuestionsQuizs = array();
	}

	/**
	 * Gets an array of QuestionsQuiz objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Question has previously been saved, it will retrieve
	 * related QuestionsQuizs from storage. If this Question is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array QuestionsQuiz[]
	 * @throws     PropelException
	 */
	public function getQuestionsQuizs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collQuestionsQuizs === null) {
			if ($this->isNew()) {
			   $this->collQuestionsQuizs = array();
			} else {

				$criteria->add(QuestionsQuizPeer::ID_QUESTION, $this->id_question);

				QuestionsQuizPeer::addSelectColumns($criteria);
				$this->collQuestionsQuizs = QuestionsQuizPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(QuestionsQuizPeer::ID_QUESTION, $this->id_question);

				QuestionsQuizPeer::addSelectColumns($criteria);
				if (!isset($this->lastQuestionsQuizCriteria) || !$this->lastQuestionsQuizCriteria->equals($criteria)) {
					$this->collQuestionsQuizs = QuestionsQuizPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastQuestionsQuizCriteria = $criteria;
		return $this->collQuestionsQuizs;
	}

	/**
	 * Returns the number of related QuestionsQuiz objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related QuestionsQuiz objects.
	 * @throws     PropelException
	 */
	public function countQuestionsQuizs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collQuestionsQuizs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(QuestionsQuizPeer::ID_QUESTION, $this->id_question);

				$count = QuestionsQuizPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(QuestionsQuizPeer::ID_QUESTION, $this->id_question);

				if (!isset($this->lastQuestionsQuizCriteria) || !$this->lastQuestionsQuizCriteria->equals($criteria)) {
					$count = QuestionsQuizPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collQuestionsQuizs);
				}
			} else {
				$count = count($this->collQuestionsQuizs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a QuestionsQuiz object to this object
	 * through the QuestionsQuiz foreign key attribute.
	 *
	 * @param      QuestionsQuiz $l QuestionsQuiz
	 * @return     void
	 * @throws     PropelException
	 */
	public function addQuestionsQuiz(QuestionsQuiz $l)
	{
		if ($this->collQuestionsQuizs === null) {
			$this->initQuestionsQuizs();
		}
		if (!in_array($l, $this->collQuestionsQuizs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collQuestionsQuizs, $l);
			$l->setQuestion($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Question is new, it will return
	 * an empty collection; or if this Question has previously
	 * been saved, it will retrieve related QuestionsQuizs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Question.
	 */
	public function getQuestionsQuizsJoinQuiz($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collQuestionsQuizs === null) {
			if ($this->isNew()) {
				$this->collQuestionsQuizs = array();
			} else {

				$criteria->add(QuestionsQuizPeer::ID_QUESTION, $this->id_question);

				$this->collQuestionsQuizs = QuestionsQuizPeer::doSelectJoinQuiz($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(QuestionsQuizPeer::ID_QUESTION, $this->id_question);

			if (!isset($this->lastQuestionsQuizCriteria) || !$this->lastQuestionsQuizCriteria->equals($criteria)) {
				$this->collQuestionsQuizs = QuestionsQuizPeer::doSelectJoinQuiz($criteria, $con, $join_behavior);
			}
		}
		$this->lastQuestionsQuizCriteria = $criteria;

		return $this->collQuestionsQuizs;
	}

	/**
	 * Clears out the collQuizusrs collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addQuizusrs()
	 */
	public function clearQuizusrs()
	{
		$this->collQuizusrs = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collQuizusrs collection (array).
	 *
	 * By default this just sets the collQuizusrs collection to an empty array (like clearcollQuizusrs());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initQuizusrs()
	{
		$this->collQuizusrs = array();
	}

	/**
	 * Gets an array of Quizusr objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Question has previously been saved, it will retrieve
	 * related Quizusrs from storage. If this Question is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Quizusr[]
	 * @throws     PropelException
	 */
	public function getQuizusrs($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collQuizusrs === null) {
			if ($this->isNew()) {
			   $this->collQuizusrs = array();
			} else {

				$criteria->add(QuizusrPeer::ID_QUESTION, $this->id_question);

				QuizusrPeer::addSelectColumns($criteria);
				$this->collQuizusrs = QuizusrPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(QuizusrPeer::ID_QUESTION, $this->id_question);

				QuizusrPeer::addSelectColumns($criteria);
				if (!isset($this->lastQuizusrCriteria) || !$this->lastQuizusrCriteria->equals($criteria)) {
					$this->collQuizusrs = QuizusrPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastQuizusrCriteria = $criteria;
		return $this->collQuizusrs;
	}

	/**
	 * Returns the number of related Quizusr objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Quizusr objects.
	 * @throws     PropelException
	 */
	public function countQuizusrs(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collQuizusrs === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(QuizusrPeer::ID_QUESTION, $this->id_question);

				$count = QuizusrPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(QuizusrPeer::ID_QUESTION, $this->id_question);

				if (!isset($this->lastQuizusrCriteria) || !$this->lastQuizusrCriteria->equals($criteria)) {
					$count = QuizusrPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collQuizusrs);
				}
			} else {
				$count = count($this->collQuizusrs);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Quizusr object to this object
	 * through the Quizusr foreign key attribute.
	 *
	 * @param      Quizusr $l Quizusr
	 * @return     void
	 * @throws     PropelException
	 */
	public function addQuizusr(Quizusr $l)
	{
		if ($this->collQuizusrs === null) {
			$this->initQuizusrs();
		}
		if (!in_array($l, $this->collQuizusrs, true)) { // only add it if the **same** object is not already associated
			array_push($this->collQuizusrs, $l);
			$l->setQuestion($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Question is new, it will return
	 * an empty collection; or if this Question has previously
	 * been saved, it will retrieve related Quizusrs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Question.
	 */
	public function getQuizusrsJoinAnswer($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collQuizusrs === null) {
			if ($this->isNew()) {
				$this->collQuizusrs = array();
			} else {

				$criteria->add(QuizusrPeer::ID_QUESTION, $this->id_question);

				$this->collQuizusrs = QuizusrPeer::doSelectJoinAnswer($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(QuizusrPeer::ID_QUESTION, $this->id_question);

			if (!isset($this->lastQuizusrCriteria) || !$this->lastQuizusrCriteria->equals($criteria)) {
				$this->collQuizusrs = QuizusrPeer::doSelectJoinAnswer($criteria, $con, $join_behavior);
			}
		}
		$this->lastQuizusrCriteria = $criteria;

		return $this->collQuizusrs;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Question is new, it will return
	 * an empty collection; or if this Question has previously
	 * been saved, it will retrieve related Quizusrs from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Question.
	 */
	public function getQuizusrsJoinQuiz($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(QuestionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collQuizusrs === null) {
			if ($this->isNew()) {
				$this->collQuizusrs = array();
			} else {

				$criteria->add(QuizusrPeer::ID_QUESTION, $this->id_question);

				$this->collQuizusrs = QuizusrPeer::doSelectJoinQuiz($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(QuizusrPeer::ID_QUESTION, $this->id_question);

			if (!isset($this->lastQuizusrCriteria) || !$this->lastQuizusrCriteria->equals($criteria)) {
				$this->collQuizusrs = QuizusrPeer::doSelectJoinQuiz($criteria, $con, $join_behavior);
			}
		}
		$this->lastQuizusrCriteria = $criteria;

		return $this->collQuizusrs;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAnswers) {
				foreach ((array) $this->collAnswers as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collCorrectAnswerQuestions) {
				foreach ((array) $this->collCorrectAnswerQuestions as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collQuestionsQuizs) {
				foreach ((array) $this->collQuestionsQuizs as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collQuizusrs) {
				foreach ((array) $this->collQuizusrs as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAnswers = null;
		$this->collCorrectAnswerQuestions = null;
		$this->collQuestionsQuizs = null;
		$this->collQuizusrs = null;
			$this->aDificulty = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseQuestion:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseQuestion::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseQuestion
