<?php


/**
 * Skeleton subclass for representing a row from the 'sf_guard_user_profile' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Jan 24 19:32:32 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sfGuardPlugin.lib.model
 */
class sfGuardUserProfile extends BasesfGuardUserProfile {
    
  public function __toString()
  {
    return $this->getFirstName();
  }
  

} // sfGuardUserProfile
