<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/01/31 23:20:51
sfConfig::add(array(
  'mod_sfguardpermission_enabled' => true,
  'mod_sfguardpermission_view_class' => 'sfPHP',
));
