<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/01/31 23:25:15
sfConfig::add(array(
  'mod_correct_answer_question_enabled' => true,
  'mod_correct_answer_question_view_class' => 'sfPHP',
));
