<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/01/31 23:18:53
sfConfig::add(array(
  'mod_dificulty_quiz_enabled' => true,
  'mod_dificulty_quiz_view_class' => 'sfPHP',
));
