<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/02/02 23:19:27
sfConfig::add(array(
  'app_sf_guard_plugin_routes_register' => 'on',
  'app_sf_guard_plugin_profile_class' => 'sfGuardUserProfile',
  'app_sf_guard_plugin_profile_field_name' => 'user_id',
  'app_sf_guard_plugin_signin_form' => 'sfGuardFormSignin',
));
