<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/02/02 23:19:28

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=bbvaquiz;host=localhost',
  'username' => 'root',
  'password' => 'root',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
