generator:
  class: sfPropelGenerator
  param:
    model_class:           answer
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              answer
    plural:                answers
    route_prefix:          answer
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
        answer: { label: Respuesta,with_empty: vacio}
        question_name: { label: Pregunta}
        id_question: { label: Pregunta}
        correct: {label: Respuesta correcta}
      list:   
        title: Listado de respuestas
        peer_method: doSelectJoinQuestion
        title: Administrador de respuestas
        display: [answer, question_name, correct]
        max_per_page: 9
        
      filter:  ~
      form:
        display:
          Contenido: [answer, id_question, correct]
      edit:    
        title: Edición de "%%answer%%"
        
      new:     
        title: Nueva respuesta
        
