generator:
  class: sfPropelGenerator
  param:
    model_class:           DificultyQuiz
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              DificultyQuiz
    plural:                DificultyQuizs
    route_prefix:          dificulty_quiz
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
        title: Listado de dificultades por actividad
        fields:  
          quiz: { label: Actividad}
          easy: { label: Facíl}
          medium: {label: Medio}
          hard: {label: Dificil}
        peer_method:  doSelectJoinQuiz
        display:  [quiz, easy, medium, hard]
      filter:  
        fields:  
          id_quiz: { label: Actividad}
          easy: { label: Facíl}
          medium: {label: Medio}
          hard: {label: Dificil}
      form:    
        display:
          Content: [id_quiz, easy, medium, hard]
          
      edit:   
         title: Edición de dificultad para "%%id_quiz%%"
         fields:  
          id_quiz: { label: Actividad}
          easy: { label: Facíl}
          medium: {label: Medio}
          hard: {label: Dificil}
      new:     
        title: Nueva opción de dificultad para la actividad
        fields:  
          id_quiz: { label: Actividad}
          easy: { label: Facíl}
          medium: {label: Medio}
          hard: {label: Dificil}