<?php


/**
 * Skeleton subclass for representing a row from the 'answer' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/28/12 13:03:28
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Answer extends BaseAnswer {

	/**
	 * Initializes internal state of Answer object.
	 * @see        parent::__construct()
	 */
	public function __construct()
	{
		// Make sure that parent constructor is always invoked, since that
		// is where any default values for this object are set.
		parent::__construct();
	}
        
        public function __toString()
        {
            return ($this->getAnswer() != null) ? $this->getAnswer() : '' ;
            
        }
        
        public function getQuestionName(){
            return $this->getQuestion();
        }

} // Answer
