<?php


/**
 * Skeleton subclass for performing query and update operations on the 'bonus_quiz' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Mar 19 16:35:36 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class BonusQuizPeer extends BaseBonusQuizPeer {

} // BonusQuizPeer
