<?php


/**
 * Skeleton subclass for representing a row from the 'dificulty_quiz' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Jan 31 20:30:50 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class DificultyQuiz extends BaseDificultyQuiz {
    public function __toString(){
        return "";
    }

} // DificultyQuiz
