<?php


/**
 * Skeleton subclass for representing a row from the 'dificulty' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/28/12 13:03:29
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Dificulty extends BaseDificulty {
    public function __toString()
    {
       return ($this->getName() != null) ? $this->getName() : '' ;
    }
    
    public function getDificultyName(){
            return $this->getName();
     }

} // Dificulty
