<?php


/**
 * Skeleton subclass for representing a row from the 'position' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Feb 12 23:20:39 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Position extends BasePosition {
    
     public function __toString()
     {
            return $this->getPosition();
            
     }

} // Position
