<?php


/**
 * Skeleton subclass for representing a row from the 'question' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/28/12 13:03:29
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Question extends BaseQuestion {
    public function __toString(){
        return ($this->getQuestion() != null) ? $this->getQuestion() : '' ;
    }
    
    public function getQuestionName(){
        return $this->getQuestion();
    }
    
     public function getDificultyName(){
            return $this->getDificulty();
     }
    

} // Question
