<?php


/**
 * Skeleton subclass for representing a row from the 'quiz' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 09/28/12 13:03:30
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Quiz extends BaseQuiz {

    public function __toString(){
        return $this->getDescription();
    }
    
     public function getQuizName(){
            return $this->getDescription();
     }
} // Quiz
