<?php


/**
 * Skeleton subclass for performing query and update operations on the 'quizlog' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Feb  3 03:42:51 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class QuizlogPeer extends BaseQuizlogPeer {

} // QuizlogPeer
