propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  area:
    _attributes: { phpName: Area }
    id_area: { phpName: IdArea, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    area: { phpName: Area, type: VARCHAR, size: '145', required: true }
  depto:
    _attributes: { phpName: Depto }
    id_depto: { phpName: IdDepto, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    depto: { phpName: Depto, type: VARCHAR, size: '200', required: true }
  position:
    _attributes: { phpName: Position }
    id_position: { phpName: IdPosition, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    position: { phpName: Position, type: VARCHAR, size: '100', required: true }
  zone:
    _attributes: { phpName: Zone }
    id_zone: { phpName: IdZone, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    zone: { phpName: Zone, type: VARCHAR, size: '100', required: true }
