generator:
  class: sfPropelGenerator
  param:
    model_class:           instructions
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              instructions
    plural:                instructionss
    route_prefix:          instructions
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
          id_instruction:   { label: Id }
          instruction:   { label: Instrucción }
         
      list:    
        title: Instrucciones  
      filter:  ~
      form:    ~
      edit:    
        title: Editar instrucción
      new:     
        title: Nueva instrucción
