<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/01/31 23:16:12

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:dbname=bbvaquiz;host=localhost',
  'username' => 'root',
  'password' => 'root',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
